### ISSUE TITLE
Databas problem.

### ISSUE THREAD

**Issue by MyffinnMann** [MyffinnMann/Log-Analysis-with-LLM#39]
Skapas på fel ställe (för mig på skrivbordet), skapas en ny hash för varje körning även om användaren redan finns, därmed finns där omkring 300 + hashade lösenord i databas filen.

**Comment by HackermanOfTheBaer** [comment]
missade att denna fanns som benämnde det med att den skapa mappen på fel ställe, men som Samuel skrev. Den biten är fixad, har dock inte kollat på biten att de skapas en ny hashning varje gång.

**Comment by ibab20** [comment]
Flera hash skapas inte längre, kommer att stänga detta issue
