### ISSUE TITLE
Log in Bug

### ISSUE THREAD

**Issue by MyffinnMann** [MyffinnMann/Log-Analysis-with-LLM#45]
Ibland när man slår in anv, lösen och trycker logga in så laddas sidan om och man måste slå in det igen.

**Comment by HackermanOfTheBaer** [comment]
Som det verkar när jag har testat lite så uppkommer problemet bara första gången man ska logga in. Backar man tillbaka eller stänger ner sidan och laddar in login sidan på nytt med aldrig stängt ner webläsaren uppstår inte problemet.
Däremot om man stänger ner webläsaren och försöker återigen så återkommer problemet på nytt men maximalt 1 gång.

**Comment by HackermanOfTheBaer** [comment]
FÖRSTA (fail):
127.0.0.1 - - [11/Nov/2024 15:31:35] "OPTIONS /login HTTP/1.1" 200 -
Anslutning till SQLite-databasen lyckades.

debuggggg

<SecureCookieSession {'user_id': 'user_2', 'user_directory': '..\\backend\\db\\user_2', 'vector_db': None, 'ollama_instance': None}>

debuggggg

127.0.0.1 - - [11/Nov/2024 15:31:35] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [11/Nov/2024 15:31:35] "GET /PRE_chat.html HTTP/1.1" 304 -
127.0.0.1 - - [11/Nov/2024 15:31:35] "GET /css/style.css HTTP/1.1" 304 -
127.0.0.1 - - [11/Nov/2024 15:31:35] "GET /css/index.css HTTP/1.1" 304 -
127.0.0.1 - - [11/Nov/2024 15:31:35] "GET /css/chat.css HTTP/1.1" 304 -
127.0.0.1 - - [11/Nov/2024 15:31:35] "GET /css/login.css HTTP/1.1" 304 -
127.0.0.1 - - [11/Nov/2024 15:31:35] "GET /favicon.ico HTTP/1.1" 404 -


ANDRA (sucess):

Anslutning till SQLite-databasen lyckades.

debuggggg

<SecureCookieSession {'user_id': 'user_2', 'user_directory': '..\\backend\\db\\user_2', 'vector_db': None, 'ollama_instance': None}>

debuggggg

127.0.0.1 - - [11/Nov/2024 15:32:17] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [11/Nov/2024 15:32:17] "GET /PRE_chat.html HTTP/1.1" 200 -
127.0.0.1 - - [11/Nov/2024 15:32:17] "GET /css/style.css HTTP/1.1" 304 -
127.0.0.1 - - [11/Nov/2024 15:32:17] "GET /css/index.css HTTP/1.1" 304 -
127.0.0.1 - - [11/Nov/2024 15:32:17] "GET /css/chat.css HTTP/1.1" 304 -
127.0.0.1 - - [11/Nov/2024 15:32:17] "GET /css/login.css HTTP/1.1" 304 -
