### ISSUE TITLE
Error med session id skapandet

### ISSUE THREAD

**Issue by HackermanOfTheBaer** [MyffinnMann/Log-Analysis-with-LLM#84]
![image](https://github.com/user-attachments/assets/72040e56-7875-45ae-8a90-3558903c9535)
Uppstår när man loggar in, sker i DB filen. Vet inte vad mer vi använder den tabellen till atm.

**Comment by MyffinnMann** [comment]
@ibab20 Löst?

**Comment by ibab20** [comment]
Oops, har inte sett det, men tror jag vet vad är problemet, jag kan lösa det
